### ISSUE TITLE
Bug: selection of images more than count not fixed

### ISSUE THREAD

**Issue by Anu07** [vansikrishna/Multimager#2]
Hello

If I have set max count as 5.If I select 4 images from gallery and  add 2 more images from camera or again the gallery.It will allow selection which is wrong.Kindly help.

**Comment by vansikrishna** [comment]
@Anu07 Thanks for the input. Its fixed in new version 1.0.3. Plz update

**Comment by Anu07** [comment]
Sorry,But I am using the latest one.Still facing the issue.I have selected 4 images from gallery and displayed.Then again I selected new images from gallery(it should allow only 1 image to be selected firstly).But it will allow me to select 5 images again.which is incorrect.

**Comment by vansikrishna** [comment]
While creating the intent for GalleryActivity, if you are passing the picker limit as 5, it will not allow more than that. First time you selected 4 and displayed them. Second time you are using the same intent (which has the limit set as 5) so it will allow you to pick 5. May be you should dynamically control the limit while passing them in the intent.

**Comment by Anu07** [comment]
Yes it was the same thing I was pointing.Anyways thanks for suggestion I'll definitely try.


Thanks
